# > 圆通速递<微信小程序> - YTO
^https?:\/\/mec\.yto\.net\.cn\/api\/market\/queryActivityPromotion url reject-dict
^https?:\/\/mec\.yto\.net\.cn\/api\/officalWeb\/content\/query url reject-dict

hostname = mec.yto.net.cn