# > 亚马逊 - AMAZON
^https?:\/\/api-cslp-emt\.amazon\.cn\/gateway\/recommend url reject-dict
^https?:\/\/api-cslp-emt\.amazon\.cn\/gateway\/config\/getUpdatePopupConfig url reject-dict
^https?:\/\/api-cslp-emt\.amazon\.cn\/gateway\/content\/widget\/(?>popup|floatingWindow) url reject-dict

hostname = api-cslp-emt.amazon.cn