# > 功能类 - FUNCTIONAL
^https?:\/\/(raw|gist)\.githubusercontent\.com\/ url request-header (\r\n)Accept-Language:.+(\r\n) request-header $1Accept-Language: en-us$2
^https?:\/\/github\.com\/ url request-header (\r\n)Accept-Language:.+(\r\n) request-header $1Accept-Language: en-us$2
^https?:\/\/doh\.pub\/dns-query\? url reject

hostname = raw.githubusercontent.com, gist.githubusercontent.com, github.com, doh.pub