# > 功能类 - FUNCTIONAL
^https?:\/\/119\.29\.29\.\d+\/d\?dn=[a-z0-9]+&clientip=\d&ttl=\d&query=1&id=\d+&sdk=\d+_\d+\.\d+\.\d+&alg=des url 302 http://119.29.29.$0/d?dn=$1&clientip=$2&ttl=$3&query=0&id=$4&sdk=$5_$6.$7.$8&alg=des
^https?:\/\/(raw|gist)\.githubusercontent\.com\/ url request-header (\r\n)Accept-Language:.+(\r\n) request-header $1Accept-Language: en-us$2
^https?:\/\/github\.com\/ url request-header (\r\n)Accept-Language:.+(\r\n) request-header $1Accept-Language: en-us$2

hostname = 119.29.29.*, raw.githubusercontent.com, gist.githubusercontent.com, github.com