# > 去哪儿 - QUNAR
^https?:\/\/qde\.qunar\.com\/preload url reject-200
^https?:\/\/homefront\.qunar\.com\/front\/splash\/ad url reject-dict
^https?:\/\/client\.qunar\.com\/pitcher-proxy\?qrt=p_splashAd url reject
# 首页瀑布流
^https?:\/\/slugger\.qunar\.com\/slugger-proxy\?qrt=content_api_common_desert_damo_getPostList url reject-200
# 我的页底部推荐
^https?:\/\/slugger\.qunar\.com\/slugger-proxy\?qrt=p_feedlist_recommend url reject-dict

hostname = qde.qunar.com, homefront.qunar.com, client.qunar.com, qimgs.qunarzz.com, slugger.qunar.com