# > 海南航空 - HNAIR
^https?:\/\/m\.hnair\.com\/cms\/config\/standard\/(?>homePop|recommend|share|startPic) url reject-dict
# 首页-产品专区 会员专享
^https?:\/\/m\.hnair\.com\/cms\/config\/standard\/act\/act url reject-dict
# 首页-中间横幅
^https?:\/\/m\.hnair\.com\/cms\/config\/standard\/slider\/slider url reject-dict
# 首页-滚动消息
^https?:\/\/app\.hnair\.com\/mapp\/webservice\/v1\/common\/news\/list url reject

hostname = m.hnair.com, app.hnair.com