# > 上银美好生活 - BOSCLIFE
^https?:\/\/mpaas1\.bosc\.cn(:\d+)?\/loggw url reject-200
^https?:\/\/dfg\.bosc\.cn(:\d+)?\/public\/sdkConfig\/get url reject-dict
^https?:\/\/gdlf\.bosc\.cn(:\d+)?\/static\/upload\/pro\/resource\/(?!1762370|1939565)\w+\.jpg$ url reject
^https?:\/\/mgs1\.bosc\.cn(:\d+)?\/mgw url script-response-header https://raw.githubusercontent.com/zirawell/R-Store/main/Res/Scripts/AntiAd/mgw.js

hostname = mpaas1.bosc.cn, dfg.bosc.cn, gdlf.bosc.cn, mgs1.bosc.cn