# > 淘宝闪购 - TBTO
^https?:\/\/amdc\.m\.ele\.me\/amdc\/mobileDispatch url reject-dict
^https?:\/\/g\.alicdn\.com\/TBTakeout\/et-store\/(\d+.)*\/weex\/store-brand-popup url reject-dict
^https?:\/\/nr-op\.elemecdn\.com\/eleme\/transformer\/templates\/\w_eleme_home_yolo_popup url reject
^https?:\/\/(?>nr-op|cube)\.elemecdn\.com\/image\/.*\.(png|jpeg|jpg|gif)\?x-oss-process=image\/resize,m_fill,w_\d+,h_\d+\/($|format,webp\/$) url reject-img

hostname = amdc.m.ele.me, g.alicdn.com, nr-op.elemecdn.com, cube.elemecdn.com