# > 每日英语听力 - FRDIC
^https?:\/\/static(-main)?\.frdic\.com\/bg\/startpage url reject
^https?:\/\/api\.eudic\.net\/api\/v\d\/appsupport\/StartupConfig url reject

hostname = static.frdic.com, static-main.frdic.com, api.eudic.net